version: '3'

services:
  db:
    image: postgres
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=dss
      - POSTGRES_PASSWORD=dss
      - POSTGRES_DB=users

  web:
    build: .
    volumes:
      - .:/code
    
    environment:
      - DATABASE_URL=postgres://dss:dss@db:5432/users
    ports:
      - "3000:3000"
    depends_on:
      - db